### ISSUE TITLE
ml4gw-quickstart comments and an s3cmd installation issue

### ISSUE THREAD

**Issue by VasSkliris** [ML4GW/quickstart#1]
- The cloning command better to be replaced with the http one because it doesn't allow access
- The repo cloning creates a repo called `quickstart` not `ml4gw-quickstart`
- Finally when I run the makefile, there is the following error message at the s3cmd installation:

```
Using xml.etree.ElementTree for XML processing
running install
/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 30] Read-only file system: '/cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/test-easy-install-238914.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /cvmfs/software.igwn.org/conda/envs/igwn/lib/python3.10/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

make: *** [Makefile:55: install-s3cmd] Error 1
```

**Comment by VasSkliris** [comment]
Also after runnin `ecp-get-cert -k` I get the following:
```
(igwn) [vasileios.skliris@ldas-pcdev12 ~]$ ecp-get-cert -k
ERROR:requests_gssapi.gssapi_:generate_request_header(): stepping context failed:
Traceback (most recent call last):
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_gssapi/gssapi_.py", line 161, in generate_request_header
    gss_response = self.context[host].step()
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 131, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 584, in step
    return self._initiator_step(token=token)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 606, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 188, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
ERROR:requests_gssapi.gssapi_:Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
Traceback (most recent call last):
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_gssapi/gssapi_.py", line 161, in generate_request_header
    gss_response = self.context[host].step()
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 131, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 584, in step
    return self._initiator_step(token=token)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 606, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 188, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
WARNING:requests_gssapi.gssapi_:HTTPSPNEGOAuth: Opportunistic auth failed with stepping context failed: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired -> sending request without adding Authorization header. Will try again if it results in a 401.
ERROR:requests_gssapi.gssapi_:generate_request_header(): stepping context failed:
Traceback (most recent call last):
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_gssapi/gssapi_.py", line 163, in generate_request_header
    gss_response = self.context[host].step(_negotiate_value(response))
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 131, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 584, in step
    return self._initiator_step(token=token)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 606, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 188, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
ERROR:requests_gssapi.gssapi_:Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
Traceback (most recent call last):
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_gssapi/gssapi_.py", line 163, in generate_request_header
    gss_response = self.context[host].step(_negotiate_value(response))
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 131, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 584, in step
    return self._initiator_step(token=token)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 606, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 188, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
ERROR:requests_gssapi.gssapi_:generate_request_header(): stepping context failed:
Traceback (most recent call last):
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_gssapi/gssapi_.py", line 163, in generate_request_header
    gss_response = self.context[host].step(_negotiate_value(response))
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 131, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 584, in step
    return self._initiator_step(token=token)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 606, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 188, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
ERROR:requests_gssapi.gssapi_:Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
Traceback (most recent call last):
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_gssapi/gssapi_.py", line 163, in generate_request_header
    gss_response = self.context[host].step(_negotiate_value(response))
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/_utils.py", line 131, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 584, in step
    return self._initiator_step(token=token)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/gssapi/sec_contexts.py", line 606, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 188, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (100002): Ticket expired
Traceback (most recent call last):
  File "/cvmfs/software.igwn.org/conda/envs/igwn/bin/ecp-get-cert", line 10, in <module>
    sys.exit(main())
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/ciecplib/tool/ecp_get_cert.py", line 205, in main
    cert, key = get_cert(
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/ciecplib/requests.py", line 65, in _wrapper
    return func(*args, session=sess, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/ciecplib/ui.py", line 139, in get_cert
    cookie = get_cookie(spurl, session=sess, debug=debug)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/ciecplib/requests.py", line 65, in _wrapper
    return func(*args, session=sess, **kwargs)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/ciecplib/ui.py", line 82, in get_cookie
    sess.ecp_authenticate(
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_ecp/session.py", line 115, in ecp_authenticate
    return self.auth._authenticate_session(
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_ecp/auth.py", line 218, in _authenticate_session
    self._authenticate(session, url=url)
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_ecp/auth.py", line 259, in _authenticate
    return ecp_authenticate(
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_ecp/ecp.py", line 202, in authenticate
    resp2 = _send(
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests_ecp/ecp.py", line 81, in _send
    response.raise_for_status()
  File "/cvmfs/software.igwn.org/conda/envs/igwn-py310-20240410/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://login.ligo.org/idp/profile/SAML2/SOAP/ECP

```

**Comment by EthanMarx** [comment]
Thanks Vassilis. Can I ask which cluster you were installing on?

**Comment by VasSkliris** [comment]
CIT
